package fr.eni.javaee.auctions.bll;

public interface CodeErreurBLLUtilisateur {
	
	int REGLES_UTILISATEUR_PSEUDO_ERREUR = 20_001;
	int REGLES_UTILISATEUR_NOM_ERREUR = 20_002;
	int REGLES_UTILISATEUR_PRENOM_ERREUR = 20_003;
	int REGLES_UTILISATEUR_EMAIL_ERREUR = 20_004;
	int REGLES_UTILISATEUR_TELEPHONE_ERREUR = 20_005;
	int REGLES_UTILISATEUR_RUE_ERREUR = 20_006;
	int REGLES_UTILISATEUR_CODE_POSTAL_ERREUR = 20_007;
	int REGLES_UTILISATEUR_VILLE_ERREUR = 20_008;
	int REGLES_UTILISATEUR_MOT_DE_PASSE_ERREUR = 20_009;
	int REGLES_UTILISATEUR_VALIDER_MDP_ERREUR = 20_010;

}
