package fr.eni.javaee.auctions.bll;

public interface CodeErreurBLLArticle {

	int REGLES_ARTICLE_NOMARTICLE_ERREUR = 40000;
	int REGLES_ARTICLE_DESCRIPTION_ERREUR = 40001;
	int REGLES_ARTICLE_MISEAPRIX_ERREUR = 40002;
	int REGLES_ARTICLE_DATEDEBUTENCHERE_ERREUR = 40003;
	int REGLES_ARTICLE_DATEFINENCHERE_ERREUR = 40004;
	int REGLES_ARTICLE_RUE_ERREUR = 40005;
	int REGLES_ARTICLE_CODEPOSTAL_ERREUR = 40006;
	int REGLES_ARTICLE_VILLE_ERREUR = 40007;
	
	
}
